{{- range .Values.frankenphp.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "diazoxide-symfony.fullname" $ }}-{{ .name }}-cronjob
  labels:
    {{- include "diazoxide-symfony.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }} # MM HH DD MM WKD -- Minutes, Hour, Day, Month, Weekday (eg. Sun, Mon)
  successfulJobsHistoryLimit: 1 # how many completed jobs should be kept
  failedJobsHistoryLimit: 1 # how many failed jobs should be kept
  concurrencyPolicy: Forbid # Choose Forbid if you don't want concurrent executions of your Job
  suspend: false # Here you can suspend cronjob without deliting it

  # The amount of time that Kubernetes can miss and still start a job.
  # If Kubernetes missed too many job starts (100)
  # then Kubernetes logs an error and does not start any future jobs.
  startingDeadlineSeconds: 300 # if a job hasn't started in this many seconds, skip
  
  jobTemplate:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "diazoxide-symfony.selectorLabels" $ | nindent 8 }}
    spec:
      parallelism: 1 # How many pods will be instantiated at once.
      completions: 1 # How many containers of the job are instantiated one after the other (sequentially) inside the pod.
      backoffLimit: 3 # Maximum pod restarts in case of failure
      activeDeadlineSeconds: 1800 # Limit the time for which a Job can continue to run
      template:
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "diazoxide-symfony.serviceAccountName" $ }}
          restartPolicy: Never
          containers:
            - name: {{ $.Chart.Name }}-cronjob
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.frankenphp.image.repository }}:{{ $.Values.frankenphp.image.tag }}"
              imagePullPolicy: {{ $.Values.frankenphp.image.pullPolicy }}
              command:
                {{- toYaml .command | nindent 16 }}
              args:
                {{- toYaml .args | nindent 16 }}
              env:
                {{- include "diazoxide-symfony.env" $ | nindent 16 }}
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}

{{- end }}
