{{- range .Values.php.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "diazoxide-symfony.fullname" $ }}-{{ .name }}-cronjob
  labels:
    {{- include "diazoxide-symfony.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "diazoxide-symfony.selectorLabels" $ | nindent 8 }}
    spec:
      template:
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "diazoxide-symfony.serviceAccountName" $ }}
          restartPolicy: Never
          containers:
            - name: {{ $.Chart.Name }}-cronjob
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              image: "{{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.php.image.pullPolicy }}
              command:
                {{- toYaml .command | nindent 16 }}
              args:
                {{- toYaml .args | nindent 16 }}
              env:
                {{- include "diazoxide-symfony.env" $ | nindent 16 }}
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}

{{- end }}
