{{- range .Values.php.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "diazoxide-symfony.fullname" $ }}-{{.name}}-job
  labels:
    {{- include "diazoxide-symfony.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ join "," .hooks | quote }}
    "helm.sh/hook-delete-policy": {{ .hookDeletePolicy | quote }}
spec:
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "diazoxide-symfony.selectorLabelsFixtures" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diazoxide-symfony.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ $.Chart.Name }}-{{.name}}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.php.image.pullPolicy }}
          command: 
            {{- toYaml .command | nindent 12 }}
          args: 
            {{- toYaml .args | nindent 12 }}
          env:
            {{- include "diazoxide-symfony.env" $ | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
