{{ range .Values.php.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "diazoxide-symfony.fullname" $ }}-{{.name}}
  labels:
    {{- include "diazoxide-symfony.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ join "," .hooks | quote }}
    "helm.sh/hook-delete-policy": {{ .hookDeletePolicy | quote }}
spec:
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "diazoxide-symfony.selectorLabelsFixtures" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diazoxide-symfony.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ $.Chart.Name }}-{{.name}}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.php.image.pullPolicy }}
          command: 
            {{- toYaml .command | nindent 12 }}
          args: 
            {{- toYaml .args | nindent 12 }}
          env:
            - name: API_ENTRYPOINT_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-host
            - name: JWT_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-jwt-passphrase
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-jwt-public-key
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-jwt-secret-key
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-trusted-proxies
            - name: APP_ENV
              value: "dev"
            - name: APP_DEBUG
              value: "1"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-app-secret
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: php-cors-allow-origin
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: database-url
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: redis-port
            - name: MERCURE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: mercure-url
            - name: MERCURE_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: mercure-public-url
            - name: MERCURE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "diazoxide-symfony.fullname" $ }}
                  key: mercure-jwt-secret
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/bin/sleep 1; kill -QUIT 1"]
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
