apiVersion: v1
kind: Service
metadata:
  name: {{ include "diazoxide-symfony.fullname" . }}-pwa
  labels:
    {{- include "diazoxide-symfony.labelsPWA" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.pwaService.port }}
      targetPort: {{ .Values.pwaService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "diazoxide-symfony.selectorLabelsPWA" . | nindent 4 }}
